// AUTO-GENERATED — NE PAS MODIFIER MANUELLEMENT
// Genere par scripts/sync-client.ts depuis CLIENT.md
// Pour modifier: editer CLIENT.md puis lancer npm run sync-client

export const clientConfig = {
  NOM_ENTREPRISE: "Bacqueville Couverture",
  NOM_LEGAL: "BACQUEVILLE MARIO",
  SIRET: "992 124 248 00012",
  METIER: "couvreur",
  METIER_LABEL: "Couvreur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Mario",
  NOM_DIRIGEANT: "Bacqueville",
  DIPLOME_DIRIGEANT: "couvreur professionnel, peintre en batiment",
  ANNEE_CREATION: "2025",
  ANNEES_EXPERIENCE: "1",
  TELEPHONE: "06 69 32 48 81",
  EMAIL: "mario.bacqueville@gmail.com",
  ADRESSE: "2 CHEMIN DE GARDOUCH",
  CODE_POSTAL: "31290",
  VILLE: "Villefranche-de-Lauragais",
  DEPARTEMENT: "Haute-Garonne",
  REGION: "Occitanie",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 8h00-18h00, Sam: 9h00-13h00",
  ZONE_INTERVENTION: "Haute-Garonne (31) et Occitanie",
  ZONES_LISTE: "Villefranche-de-Lauragais, Toulouse, Castelnaudary, Revel, Montgiscard, Nailloux, Caraman, Verfeil",
  LATITUDE: "43.3964",
  LONGITUDE: "1.7213",
  COULEUR_PRIMAIRE_HUE: "220",
  COULEUR_PRIMAIRE_900: "oklch(0.22 0.06 220)",
  COULEUR_ACCENT_HUE: "25",
  COULEUR_ACCENT_500: "oklch(0.64 0.16 25)",
  COULEUR_FOND_50: "oklch(0.985 0.005 80)",
  FONT_TITRES: "Playfair Display",
  FONT_CORPS: "DM Sans",
  DOMAINE: "www.votre-domaine.fr",
  META_TITLE: "Bacqueville Couverture | Couvreur a Villefranche-de-Lauragais (31)",
  META_DESCRIPTION: "Couvreur a Villefranche-de-Lauragais et en Haute-Garonne (31). Bacqueville Couverture : couverture neuve, renovation de toiture, zinguerie, isolation, depannage urgent. Devis gratuit.",
  META_KEYWORDS: "couvreur Villefranche-de-Lauragais, couvreur Haute-Garonne 31, toiture 31, renovation toiture Toulouse, zinguerie Occitanie, depannage toiture 31, Bacqueville couverture",
  SCHEMA_TYPE: "RoofingContractor",
  SLOGAN: "Expert couverture en Haute-Garonne",
  ACCROCHE_HERO: "Votre Toiture — Entre de Bonnes Mains en Occitanie",
  DESCRIPTION_ENTREPRISE: "Bacqueville Couverture, couvreur professionnel base a Villefranche-de-Lauragais (31), intervient dans tout le departement de la Haute-Garonne pour la couverture neuve, la renovation, la zinguerie et le depannage urgent.",
  DESCRIPTION_FOOTER: "Couvreur a Villefranche-de-Lauragais et en Haute-Garonne (31). Devis gratuit, intervention rapide.",
  DESCRIPTION_APROPOS: "Fonde par Mario Bacqueville, Bacqueville Couverture est ne d'une passion pour les metiers de la couverture et du batiment.",
  SERVICE_1_TITRE: "Couverture Neuve",
  SERVICE_1_DESC: "Installation complete de votre toiture en ardoise, tuile ou zinc, avec une finition soignee et durable.",
  SERVICE_2_TITRE: "Renovation de Toiture",
  SERVICE_2_DESC: "Refection partielle ou totale de votre couverture pour redonner etancheite et esthetique a votre toit.",
  SERVICE_3_TITRE: "Zinguerie",
  SERVICE_3_DESC: "Pose et reparation de gouttieres, descentes EP, cheneaux, noues et abergements en zinc ou cuivre.",
  SERVICE_4_TITRE: "Isolation de Toiture",
  SERVICE_4_DESC: "Isolation thermique par l'interieur ou l'exterieur (sarking) pour ameliorer le confort et reduire la facture energetique.",
  SERVICE_5_TITRE: "Depannage & Urgence",
  SERVICE_5_DESC: "Intervention rapide pour fuites, tuiles cassees, bachage d'urgence et reparations suite a intemperies.",
  SERVICE_6_TITRE: "Demoussage & Entretien",
  SERVICE_6_DESC: "Nettoyage, traitement anti-mousse et hydrofuge pour prolonger la duree de vie de votre toiture.",
  GOOGLE_MAPS_URL: "",
  GOOGLE_REVIEWS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  PINTEREST_URL: "",
  TEMOIGNAGE_1_NOM: "M. Fabre",
  TEMOIGNAGE_1_VILLE: "Villefranche-de-Lauragais",
  TEMOIGNAGE_1_TEXTE: "Bacqueville Couverture a refait entierement notre toiture. Le travail est impeccable, Mario est ponctuel et soigneux. Nous recommandons sans hesiter !",
  TEMOIGNAGE_1_NOTE: "5",
  TEMOIGNAGE_2_NOM: "Famille Cassagne",
  TEMOIGNAGE_2_VILLE: "Toulouse",
  TEMOIGNAGE_2_TEXTE: "Intervention rapide apres une fuite. Diagnostic precis, reparation efficace et prix honnete. Un vrai professionnel de la couverture.",
  TEMOIGNAGE_2_NOTE: "5",
  TEMOIGNAGE_3_NOM: "Mme Riviere",
  TEMOIGNAGE_3_VILLE: "Castelnaudary",
  TEMOIGNAGE_3_TEXTE: "Renovation complete de notre zinguerie. Gouttieres en zinc posees avec un soin remarquable. Aucun probleme depuis, meme apres de fortes pluies.",
  TEMOIGNAGE_3_NOTE: "5",
  HEBERGEUR_NOM: "Vercel Inc.",
  HEBERGEUR_ADRESSE: "340 Pine Street, Suite 701, San Francisco, CA 94104, USA",
  HEBERGEUR_SITE: "vercel.com",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
  PACK_PHOTOS_METIER: "couvreur",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
